os: linux
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - lcov
    - astyle
    - devscripts
    - python3
    - python3-pip
    - python3-dev
    - python3.4-venv
    - doxygen
    - fakeroot
    - debhelper
    - pkg-config
    - alien
    - rpm
    - dh-make

matrix:
  include:
    - language: c
      script:
        - make
        - make test-unit
        - make test-acceptance
      
