os: linux
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - lcov
    - astyle
    - devscripts
    - python3
    - python3-pip
    - python3-dev
    - python3.4-venv
    - libboost-all-dev
    - libncurses5-dev
    - zlib1g-dev
    - doxygen
    - fakeroot
    - debhelper
    - pkg-config
    - alien
    - rpm
    - dh-make

matrix:
  include:
    - language: c
      script:
        - make wecall test-unit test-acceptance
